CREATE TABLE IF NOT EXISTS DEVICE (
  DEV_ID INT AUTO_INCREMENT,
  DEVNAME VARCHAR(10) NOT NULL,
  DEVTYPE VARCHAR(6) NOT NULL,
  PRIMARY KEY (`DEV_ID`)
);
ALTER TABLE DEVICE AUTO_INCREMENT = 10

CREATE TABLE IF NOT EXISTS XCONNECT (
  VLAN_ID INT AUTO_INCREMENT,
  DEV_LISTEN VARCHAR(10) NOT NULL,
  DEV_CONNECT VARCHAR(10) NOT NULL,
  PRIMARY KEY (`VLAN_ID`)
);
ALTER TABLE XCONNECT AUTO_INCREMENT = 10

CREATE TABLE IF NOT EXISTS HYPERVISOR (
  HYPE_ID INT AUTO_INCREMENT,
  HOST VARCHAR(20) NOT NULL,
  PRIMARY KEY (`HYPE_ID`)
);

CREATE TABLE IF NOT EXISTS VIRTUALIMAGES (
  IMG_ID INT AUTO_INCREMENT,
  IMG_PATH VARCHAR(200) NOT NULL,
  IMG_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IMG_ID`)
);
